// =============================================================================
// Auto-generated by: npx supabase gen types typescript --project-id YOUR_ID
// Run `npm run db:types` after pushing migrations to regenerate
// =============================================================================

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      organizations: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      organization_members: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      user_profiles: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      agents: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      agent_knowledge_base: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      agent_templates: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      leads: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      conversations: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      messages: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      appointments: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      pipeline_stages: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      lead_pipeline_entries: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      pipeline_transitions: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      domain_events: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      usage_records: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      usage_daily: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      audit_log: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      webhook_endpoints: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      webhook_deliveries: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      workflow_sequences: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      workflow_executions: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
      notifications: { Row: Record<string, unknown>; Insert: Record<string, unknown>; Update: Record<string, unknown>; };
    };
    Views: Record<string, never>;
    Functions: {
      increment_usage: { Args: Record<string, unknown>; Returns: void; };
      increment_daily_usage: { Args: Record<string, unknown>; Returns: void; };
      get_dashboard_stats: { Args: { p_org_id: string }; Returns: Record<string, unknown>[]; };
      snapshot_daily_usage: { Args: Record<string, never>; Returns: void; };
    };
    Enums: Record<string, never>;
  };
}
